### Cleaning and Preparing Data

In [2]:
import numpy as np
import pandas as pd

In [3]:
# some incomplete data
d = [ 'A', 'B', np.nan, 'D' ]
y = pd.Series(d)

In [9]:
y.isna() # isnll, notnull notna

0    False
1    False
2     True
3    False
dtype: bool

In [14]:
# we often use fillna
y.fillna('Q', inplace=True)

0    A
1    B
2    Q
3    D
dtype: str

In [15]:
y

0    A
1    B
2    Q
3    D
dtype: str

In [48]:
# using DataFrame
df = pd.DataFrame(np.random.randn(10, 3))
df.iloc[0:4,1] = np.nan
df.iloc[0:2,2] = np.nan
df.iloc[0,2] = df.iloc[4,0]
df

          0         1         2
0 -0.575036       NaN  0.826287
1 -0.021205       NaN       NaN
2  0.046881       NaN -1.084533
3 -0.903558       NaN  0.281927
4  0.826287 -0.527133  0.356114
5 -1.120895 -0.129256 -1.265759
6 -0.742500  0.003466  1.310649
7 -0.352572  0.225220 -1.497416
8  0.656348  0.450689  0.400018
9  0.296700  1.522385 -0.417964

In [57]:
# using fillna
df.describe()
df.fillna( df.mean() )

          0         1         2
0 -0.575036    wibble  0.826287
1 -0.021205    wibble    wibble
2  0.046881    wibble -1.084533
3 -0.903558    wibble  0.281927
4  0.826287 -0.527133  0.356114
5 -1.120895 -0.129256 -1.265759
6 -0.742500  0.003466  1.310649
7 -0.352572   0.22522 -1.497416
8  0.656348  0.450689  0.400018
9  0.296700  1.522385 -0.417964